export component ComicCard inherits Rectangle {
    in property <string> name;
    in property <image> cover;

    // in property <int> key2;
    // in property <int> key3;
    width: 100px;
    height: 140px;

    border-radius: 12px;
    background: touch.has-hover ? #f1f3f4 : transparent;

    animate background { duration: 150ms; }

    touch := TouchArea {
        width: 100%;
        height: 100%;
        mouse-cursor: MouseCursor.pointer;

        clicked => {
            // go to comic pages with the key
        }

        VerticalLayout {
            padding: 8px;
            spacing: 4px;

            Rectangle {
                width: 100%;
                height: 160px;
                border-radius: 8px;
                clip: true;

                Image {
                    width: 100%;
                    height: 100%;
                    source: cover;
                    image-fit: fill;
                }
            }

            Text {
                text: name;
                font-size: 14px;
                font-weight: 600;
                color: #202124;
                horizontal-alignment: center;
                overflow: elide;
            }
        }
    }
}
